Added snowflake common utility for ingestion
dassana-io/dassana-python pull request #50
Opened 2023-06-07 10:31 UTC by akashdeep-dassana

2023-06-07 12:16 UTC, vinay-dassana requested changes

2023-06-07 13:20 UTC, akashdeep-dassana commented on dassana/common.py
> +    res = requests.post(ingestion_service_url +"/job/"+job_id+"/"+"done", headers=headers, json={
Yup, I have set `ingestion_service_url = os.environ.get("DASSANA_INGESTION_SERVICE_URL")`
Should I hard code it if there is no such env variable or should I add `DASSANA_INGESTION_SERVICE_URL` in common of ingestion-srv?

2023-06-07 13:44 UTC, vinay-dassana commented on dassana/common.py
> +    res = requests.post(ingestion_service_url +"/job/"+job_id+"/"+"done", headers=headers, json={
for now hardcode it if not available

2023-06-07 16:43 UTC, akashdeep-dassana commented on dassana/common.py
> +    res = requests.post(ingestion_service_url +"/job/"+job_id+"/"+"done", headers=headers, json={
Problem with hardcoding is that it won't have the knowledge of dev or prod. Is there any env for deployment?

2023-06-08 10:43 UTC, vinay-dassana approved these changes

2023-06-08 10:43 UTC, merged