Bugfix and cleanup
dassana-io/dassana-python pull request #82
Opened 2023-11-06 15:23 UTC by akashdeep-dassana

2023-11-27 04:33 UTC, karthik-dassana requested changes

2023-11-27 04:38 UTC, akashdeep-dassana commented on dassana/common.py
> +        logger.debug(f"Response Status: {res.status_code}")
This was added temporarily to check the response of internal apis

2023-11-27 04:38 UTC, akashdeep-dassana commented on dassana/common.py
> +                job_result = {"failure_reason": exception_from_src, "status": "failed", "debug_log": list(self.debug_log), "pass": self.pass_counter, "fail": self.fail_counter, "error_code": "other_e
It'll always return a string. Internally python calls __str__ method of the class and we defined it ourselves to return a string.

2023-11-27 04:43 UTC, karthik-dassana commented on dassana/common.py
> +        logger.debug(f"Response Status: {res.status_code}")
retain it if @vinay-dassana  approves

2023-11-28 10:12 UTC, vinay-dassana approved these changes

2023-11-28 10:15 UTC, karthik-dassana approved these changes

2023-11-28 10:34 UTC, merged