add logging and tenable based logging
dassana-io/dassana-python pull request #94
Opened 2024-01-11 11:01 UTC by karthik-dassana

2024-01-11 11:35 UTC, yatin-dassana requested changes

2024-01-11 11:35 UTC, yatin-dassana commented on dassana/common.py
> +            "ms_defender_endpoint_alert": "alert",
alert should change to detection

2024-01-11 11:35 UTC, yatin-dassana commented on dassana/common.py
> +        scope_id_mapping = {
missing: qualys, wiz

also this dict should be a global constant

2024-01-11 11:35 UTC, yatin-dassana commented on dassana/common.py
> +                state_message["partnerTenantId"] = dassana_partner_tenant_id
this should be `tenantId`

2024-01-11 11:35 UTC, yatin-dassana commented on dassana/common.py
>      def close(self, metadata=None):
missing `self.report_state` when job close

2024-01-17 06:27 UTC, vinay-dassana requested changes

2024-01-17 06:27 UTC, vinay-dassana commented on dassana/dassana_logging.py
> +    topic_name = dassana_partner + "_LOG_EVENT_TOPIC_NAME"
`_LOG_EVENT_TOPIC_NAME` -> `_log_event_topic`

2024-01-17 06:27 UTC, vinay-dassana commented on dassana/dassana_logging.py
> +            topic_name = dassana_partner+"_LOG_EVENT_TOPIC_NAME"
reuse the var `topic_name`

2024-01-17 06:27 UTC, vinay-dassana commented on dassana/dassana_env.py
> +def get_logging_enbled():
remove this env var

2024-01-17 06:27 UTC, vinay-dassana commented on dassana/common.py
> +        raise KeyError()
do not raise any exception as KeyError

2024-01-17 06:27 UTC, vinay-dassana commented on dassana/common.py
> +        logger.info(f"Published Message with messageId: {publish_future.result(timeout=60)}")
log only on failure

2024-01-17 06:27 UTC, vinay-dassana commented on dassana/common.py
> +    def cancel_ingestion_job(self, metadata, fail_type, exception_from_src=None):
remove exception from this method

2024-01-17 06:27 UTC, vinay-dassana commented on dassana/common.py
> +        log(self.source, fail_type, scope_id=self.metadata["scope"]["scopeId"], exception=exception_from_src)
move log to `cancel_job` method

2024-01-17 07:03 UTC, vinay-dassana approved these changes

2024-01-17 07:03 UTC, vinay-dassana approved these changes

2024-01-17 07:04 UTC, yatin-dassana approved these changes

2024-01-17 07:04 UTC, merged